name: p2
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cuda-cccl_linux-64=12.9.27
  - cuda-cudart-dev_linux-64=12.9.79
  - cuda-cudart-static_linux-64=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-nvrtc=12.9.86
  - cuda-version=12.9
  - cupy=13.6.0
  - cupy-core=13.6.0
  - fastrlock=0.8.3
  - icu=75.1
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcublas=12.9.1.4
  - libcufft=11.4.1.4
  - libcurand=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - ncurses=6.5
  - numba=0.62.1
  - numpy=2.3.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.12.12
  - python_abi=3.12
  - readline=8.2
  - scipy=1.16.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025b
  - wheel=0.45.1
  - zstd=1.5.7
prefix: /home/mehmedmulalic/miniforge3/envs/p2
